[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jsol_vault = "FQARiEHe31wCxwJHYwQxjqGryvXCFx4h2hJvPeQ7QgB8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"

[[test.validator.clone]]
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"

[[test.validator.clone]]
address = "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1"
